### ISSUE TITLE
It does not work with chemacs2 

### ISSUE THREAD

**Issue by ezchi** [Ethanlinyf/General-Pure-Emacs#1]
I use [chemacs2](https://github.com/plexus/chemacs2) to try new Emacs config. But this config does not work well with it as it has too many hardcoded path. 

It will be great if this can be fixed

**Comment by Ethanlinyf** [comment]
All paths have been thoroughly reviewed and updated as required. Kindly assist in testing the latest version. Many thanks.

**Comment by ezchi** [comment]
Can't find `auctex.el`

 load("auctex.el" nil t t)
  load-with-code-conversion("/Users/ezchi/emacs-cfg/gpe/lisp/init-r-tex.el" "/Users/ezchi/emacs-cfg/gpe/lisp/init-r-tex.el" nil t)
  require(init-r-tex)
  load-with-code-conversion("/Users/ezchi/emacs-cfg/gpe/init.el" "/Users/ezchi/emacs-cfg/gpe/init.el" t t)
  load("/Users/ezchi/emacs-cfg/gpe/init.el" t t)
  (let ((init-file (expand-file-name "init.el" user-emacs-directory))) (setq package-user-dir (expand-file-name "elpa" user-emacs-directory)) (load init-file t t) (let ((chemacs-custom-file (chemacs-profile-get 'custom-file init-file))) (if (not custom-file) (progn (setq custom-file chemacs-custom-file) (if (equal custom-file init-file) nil (if (file-exists-p custom-file) nil (let (...) (save-current-buffer ... ...))) (load custom-file))))))
  chemacs-load-user-init()
  load-with-code-conversion("/Users/ezchi/.emacs.d/init.el" "/Users/ezchi/.emacs.d/init.el" t t)
  load("/Users/ezchi/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x155f5078a2f8dd>) #f(compiled-function () #<bytecode -0x1f3c61addc0da035>) t)
  command-line()
  normal-top-level()

**Comment by Ethanlinyf** [comment]
update the related code by "use-package" for the AUCTeX package.
